let legume = document.getElementById("legumes-midi");
let viande = document.getElementById("viandes-midi");
let poisson = document.getElementById("poissons-midi");
let epice = document.getElementById("epices-midi");
let fromage = document.getElementById("fromages-midi");
let fruit = document.getElementById("fruits-midi");

let legume_soir = document.getElementById("legumes-soir");
let viande_soir  = document.getElementById("viandes-soir");
let poisson_soir  = document.getElementById("poissons-soir");
let epice_soir  = document.getElementById("epices-soir");
let fromage_soir  = document.getElementById("fromages-soir");
let fruit_soir  = document.getElementById("fruits-soir");
let random_fish_or_meat =[0,1];
let fish_or_meat = Math.floor(Math.random() * random_fish_or_meat.length);
function randFood(arr) {
    let elem = Math.floor(Math.random() * arr.length)
    console.log(arr[elem]);
    return arr[elem];
}

const viandes = [
    "agneau",
    "biche",
    "boeuf",
    "caille",
    "canard",
    "cheval",
    "chevreuil",
    "dinde",
    "lapin",
    "mouton",
    "pintade",
    "porc",
    "poulet",
    "sanglier",
    "veau"
];
const epices = [
    "Ail",
    "Aneth",
    "Anis",
    "Badiane",
    "Cannelle",
    "Cardamome",
    "Carvi",
    "Colombo",
    "Coriandre",
    "Cumin",
    "Curcuma",
    "Curry",
    "Fenouil",
    "Fenugrec",
    "Galanga",
    "Garam Masala",
    "Gingembre",
    "Girofle",
    "Kororima",
    "Macis",
    "Mahaleb",
    "Moutarde graines",
    "Muscade",
    "Nigelle",
    "Paprika",
    "Pavot",
    "Piment",
    "Ras el Hanout",
    "Réglisse",
    "Safran",
    "Sésame",
    "Sumac",
    "Vanille"
    ];

    const fromages =
    [
    "A Filetta",
    "Abbaye de Belloc",
    "Abbaye de la Joie Notre-Dame",
    "Abbaye de la Pierre-qui-Vire",
    "Abbaye de Tamié",
    "Abondance",
    "Affidélice",
    "Aiguille d'Orcières",
    "Aisy cendré",
    "Amou",
    "Ardi-Gasna",
    "Arôme au vin blanc",
    "Arôme de Lyon",
    "Arthon",
    "Autun",
    "Avalin",
    "Baguette paysanne à la moutarde",
    "Banon",
    "Barberey",
    "Barousse",
    "Beaufort",
    "Beaumont",
    "Belle des champs",
    "Bessay",
    "Bethmale",
    "Bleu d'Auvergne",
    "Bleu de Costaros",
    "Bleu de Gex",
    "Bleu de Gex Haut-Jura",
    "Bleu de Laqueuille",
    "Bleu de Lavaldens",
    "Bleu de Loudes",
    "Bleu de Sainte-Foy",
    "Bleu de Termignon",
    "Bleu de Thiézac",
    "Bleu des Causses",
    "Bleu du Dévoluy",
    "Bleu du Mont-Cenis",
    "Bleu du Quercy",
    "Bleu du Vercors-Sassenage",
    "Bons Mayennais",
    "Bouille",
    "Boule des moines",
    "Boulet de Cassel",
    "Boulette d'Avesnes",
    "Boulette de la Pierre-qui-Vire",
    "Bouton de Culotte",
    "Bresse Bleu",
    "Brézain",
    "Brie de Meaux",
    "Brie de Melun",
    "Brie de Montereau",
    "Brie de Nangis",
    "Brin d'amour",
    "Briquette de l'Ecaillon",
    "Brocciu",
    "Cabécou",
    "Caillé",
    "Caillebotte",
    "Camembert de Normandie",
    "Cantal",
    "Cap Noir",
    "Caprice des Dieux",
    "Carré d'Aurillac",
    "Carré de Bonneville",
    "Carré du Vinage",
    "Carré Frais",
    "Cathare",
    "Ch'ti Crémeux",
    "Chabichou du Poitou",
    "Chambérat",
    "Chandamour",
    "Chaource",
    "Charolais",
    "Chaumes",
    "Chaussée aux moines",
    "Chavignol",
    "Chavroux",
    "Chécy",
    "Chevret",
    "Chevret du Haut-Jura",
    "Chèvreton",
    "Chevrotin",
    "Clon",
    "Comté",
    "Corsica",
    "Coulommiers",
    "Couronne Lochoise",
    "Cousteron",
    "Coutances",
    "Crémet du Cap Blanc Nez",
    "Crottin de Chavignol",
    "Dauphin",
    "Délice de la Sicalait",
    "Délice de Saint-Cyr",
    "Emmental de Savoie",
    "Epoisses",
    "Etorki",
    "Faisselle",
    "Fontainebleau",
    "Fort de Béthune",
    "Foudjou",
    "Fourmagée",
    "Fourme d'Ambert",
    "Fourme de Montbrison",
    "Fourme de Rochefort-Montagne",
    "Fourme d’Ambert",
    "Frinault",
    "Fromage aux artisons",
    "Fromage aux noix",
    "Fromage de Pays",
    "Fromage des Plaines",
    "Fromager d'Affinois",
    "Gabriel Coulet",
    "Gaperon",
    "Gaztanbera",
    "Gourmelin",
    "Grand tomachon",
    "Grataron du Beaufortain",
    "Gratte-Paille",
    "Gruyère français",
    "Jonchée",
    "Kaïkou",
    "Kiri",
    "L'Ami du Chambertin",
    "La Fournaise",
    "La Petite Raclette",
    "La Pierre Dorée",
    "La Vache qui rit",
    "Laguiole",
    "Langres",
    "Larron d'Ors",
    "Le Bleu des Basques",
    "Le Brebiou",
    "Le Coucouron",
    "Le Curé Nantais",
    "Le Délice du Chalet",
    "Le Fédou",
    "Le Graval",
    "Le Lavort",
    "Le Moulis",
    "Le Pavé du Plessis",
    "Le Petit Trôo",
    "Le Rogallais",
    "Le Rouchi à l'échalote",
    "Le Rustique",
    "Le Sire de Créquy",
    "Le Trou du Cru",
    "Lévéjac",
    "Livarot",
    "Lou Pérac",
    "Mâconnais",
    "Maroilles",
    "Mimolette",
    "Moelleux du Revard",
    "Mont Bébour",
    "Mont d'Or",
    "Mont des Cats",
    "Montbriac",
    "Montrachet",
    "Montségur",
    "Morbier Morbier",
    "Morbier",
    "Mottin charentais",
    "Moulin de Gaye",
    "Munster",
    "Murols",
    "Neufchâtel",
    "Notre Dame de la Paix",
    "Olivet",
    "Ossau-Iraty",
    "Ovalie",
    "P'tit Basque",
    "Pannes cendré",
    "Patay",
    "Pavé aux Algues de Samer",
    "Pavé corrézien",
    "Pavé d'Auge",
    "Pélardon",
    "Pérail",
    "Pérassu",
    "Persillé de Tignes",
    "Persillé des Aravis",
    "Persillé du col Bayard",
    "Persillé du Malzieu",
    "Persillé du Mont-Cenis",
    "Pétafine",
    "Petit Billy",
    "Petit Gaugry",
    "Petit moka",
    "Pic du Vieux Chaillol",
    "Picodon",
    "Pithiviers au foin",
    "Piton des Neiges",
    "Piton Maïdo",
    "Pont-l'Evêque",
    "Port-Salut",
    "Pouligny Saint-Pierre",
    "Pouligny-saint-pierre",
    "Pourri bressan",
    "Raclette",
    "Ramequin",
    "Rebarbe",
    "Reblochon",
    "Recuite",
    "Rigotte de Condrieu",
    "Rigotte de Pélussin",
    "Rocamadour",
    "Rochebaron",
    "Rocroi",
    "Rogeret des Cévennes",
    "Rollot",
    "Roquefort",
    "Roue de Ris",
    "Saint Agur",
    "Saint Albray",
    "Saint-félicien",
    "Saint-florentin",
    "Saint-gildas-des-bois",
    "Saint-laurent",
    "Saint-Nectaire",
    "Sainte-Maure de Touraine",
    "Salers",
    "Santranges-sancerre",
    "Selles-sur-Cher",
    "Société",
    "Soumaintrain",
    "St Môret",
    "Suprême des Ducs",
    "T'chiot biloute",
    "Takamaka",
    "Tarare",
    "Taupinette",
    "Thollon",
    "Ti frais des Hauts",
    "Tignard",
    "Tome de Cambrai",
    "Tome de Rhuys",
    "Tome des Bauges",
    "Tome du Champsaur",
    "Tome fraîche",
    "Tomette de Brebis",
    "Tomme au foin",
    "Tomme blanche",
    "Tomme crayeuse",
    "Tomme de Gorze",
    "Tomme de Montagne",
    "Tomme de Savoie",
    "Tomme des Pyrénées",
    "Tomme forte de Savoie",
    "Tournon-saint-pierre",
    "Tourrée de l'Aubier",
    "Tracle",
    "Trappe Échourgnac",
    "Trappiste de Belval",
    "Trappiste de Campénéac",
    "Trappiste de Laval",
    "Tricorne de Marans",
    "Truffe de Ventadour",
    "Vacherin des Bauges",
    "Valençay",
    "Vieux pané",
    "Vieux Samer",
    "Voves cendré"
    ];

    const fruits = [
        "Abricot",
        "Açaï",
        "Airelle",
        "Alkékenge",
        "Amande",
        "Ananas",
        "Aronia",
        "Avocat",
        "Banane",
        "Bergamote",
        "Bigaradier",
        "Brugnon",
        "Cacahuète",
        "Caïmite",
        "Calamondin",
        "Canneberge",
        "Carambole",
        "Cassis",
        "Cédrat",
        "Cerise",
        "Châtaigne",
        "Chérimole",
        "Citron",
        "Citron vert",
        "Clémentine",
        "Coing",
        "Combava",
        "Cranberry",
        "Datte",
        "Durian",
        "Figue",
        "Fraise",
        "Fraise des bois",
        "Framboise",
        "Fruit de la passion",
        "Fruit du dragon",
        "Goyave",
        "Grenade",
        "Grenadelle",
        "Grenadille",
        "Griotte",
        "Groseille",
        "Groseille à maquereau",
        "Icaque",
        "Jaboticaba",
        "Jacque",
        "Jamalac",
        "Jujube",
        "Kabosu",
        "Kaki",
        "Kiwi",
        "Kumquat",
        "Lime",
        "Limette",
        "Litchi",
        "Longane",
        "Lucuma",
        "Mandarine",
        "Mangoustan",
        "Mangue",
        "Marron",
        "Melon",
        "Merise",
        "Mineola",
        "Mirabelle",
        "Mûre",
        "Mûroise",
        "Myrtille",
        "Nashi",
        "Nectarine",
        "Nèfle",
        "Noisette",
        "Noix",
        "Noix de cajou",
        "Noix de coco",
        "Noix de macadamia",
        "Noix de pécan",
        "Olive",
        "Orange",
        "Orange sanguine",
        "Pamplemousse",
        "Papaye",
        "Pastèque",
        "Pêche",
        "Pepino",
        "Pignon de pin",
        "Pistache",
        "Pitaya",
        "Poire",
        "Pomelo",
        "Pomme",
        "Prune",
        "Quetsche",
        "Raisin",
        "Ramboutan",
        "Safou",
        "Salacca",
        "Sapotille",
        "Sudachi",
        "Sureau noir",
        "Tamarin",
        "Tangelo",
        "Tangerine",
        "Tangor",
        "Taxo",
        "Tomate",
        "Ugli",
        "Vanille",
        "Vavangue",
        "Yuzu",
        "Zatte"
        ];
        const legumes = [
            "Ail",
            "Artichaut",
            "Asperge",
            "Aubergine",
            "Avocat",
            "Bette",
            "Betterave",
            "Blette",
            "Brocoli",
            "Carotte",
            "Catalonia",
            "Céleri",
            "Champignon",
            "Chou-fleur",
            "Choux",
            "Citrouille",
            "Concombre",
            "Courge",
            "Courgette",
            "Cresson",
            "Crosne",
            "Dachine",
            "Daikon",
            "Échalote",
            "Endive",
            "Épinard",
            "Fenouil",
            "Fève",
            "Flageolet",
            "Giromon",
            "Haricot",
            "Igname",
            "Kancon",
            "Konbu",
            "Laitue",
            "Lentille",
            "Mâche",
            "Maïs",
            "Manioc",
            "Navet",
            "Oignon",
            "Olive",
            "Oseille",
            "Panais",
            "Patate",
            "Pâtisson",
            "Poireau",
            "Poivron",
            "Pomme de terre",
            "Potimarron",
            "Potiron",
            "Radis",
            "Rhubarbe",
            "Roquette",
            "Rutabaga",
            "Salade",
            "Salsifi",
            "Salsifis",
            "Tétragone",
            "Tomate",
            "Topinambour",
            "Udo",
            "Vitelotte",
            "Wakame",
            "Wasabi",
            "Yin Tsoï"
            ];

const poissons = [
    "Anguille",
    "Flétan",
    "Hareng",
    "Maquereau",
    "Sardine",
    "Saumon",
    "Anchois",
    "Carpe",
    "Dorade grise",
    "Espadon",
    "Esturgeon",
    "Rouget",
    "Thon",
    "Truite",
    "Dorade royale",
    "Bar",
    "Brochet",
    "Cabillaud",
    "Aiglefin",
    "Colin d’Alaska",
    "Dorade rose/sébaste",
    "Féra du Léman",
    "Flétan",
    "Lieu jaune",
    "Lieu noir",
    "Lotte",
    "Merlan",
    "Merlu",
    "Mérou",
    "Pangasius",
    "Perche du Nil / commune",
    "Requin",
    "Saint-pierre",
    "Sébaste",
    "Sole",
    "Tilapia",
    "Turbot",
    "Vivaneau",
    "Éperlan"
];

// récupéré un légume
legume.innerHTML = " <i style='color: #b96bee ' class='icofont-egg-plant icofont-3x'></i> Légumes : "+randFood(legumes);

if(random_fish_or_meat[fish_or_meat]== 0){
    // récupéré une viande 
    viande.innerHTML = " <i style='color: #bf4040 ' class='icofont-steak icofont-3x'></i> Viandes : "+randFood(viandes);
 
}else{
   // récupéré une un poisson
    poisson.innerHTML =  " <i style='color: #837a7a ' class='icofont-fish icofont-3x'></i> Poissons : "+randFood(poissons);

}

// récupéré une épices
epice.innerHTML = " <i style='color: #f29f45 ' class='icofont-plant icofont-3x'></i> Epices : "+randFood(epices);
// récupéré une fromages
fromage.innerHTML = " <i style='color: #f3d30c ' class='icofont-cheese icofont-3x'></i> Fromages : "+randFood(fromages);
// récupéré un fruit
fruit.innerHTML = " <i style='color: #6ef51f ' class='icofont-fruits icofont-3x'></i> Fruits : "+randFood(fruits);

// récupéré un légume
legume_soir.innerHTML = " <i style='color:#b96bee ' class='icofont-egg-plant icofont-3x'></i>  Légumes : "+randFood(legumes);

if(random_fish_or_meat[fish_or_meat]== 1){
    // récupéré une viande 
    viande_soir.innerHTML = " <i style='color: #bf4040 ' class='icofont-steak icofont-3x'></i> Viandes : "+randFood(viandes);
 
}else{
   // récupéré une un poisson
    poisson_soir.innerHTML =  " <i style='color: #837a7a ' class='icofont-fish icofont-3x'></i> Poissons : "+randFood(poissons);

}
// récupéré une épices
epice_soir.innerHTML = " <i style='color:#f29f45' class='icofont-plant icofont-3x'></i> Epices : "+randFood(epices);
// récupéré une fromages
fromage_soir.innerHTML = " <i style='color:#f3d30c ' class='icofont-cheese icofont-3x'></i> Fromages : "+randFood(fromages);
// récupéré un fruit
fruit_soir.innerHTML = " <i style='color:#6ef51f' class='icofont-fruits icofont-3x'></i> Fruits : "+randFood(fruits);